Gauss-Seidel_method:
	gcc -o Gauss-Seidel_method Gauss-Seidel_method.c
	gcc -o Gauss-Seidel_methodSample Gauss-Seidel_methodSample.c
	g++ -o Gauss-Seidel_method-10x10 Gauss-Seidel_method-10x10.c
	g++ -o Gauss-Seidel_method-10x10eigen Gauss-Seidel_method-10x10eigen.c

clean:
	rm -rf Gauss-Seidel_method
	rm -rf Gauss-Seidel_methodSample
	rm -rf Gauss-Seidel_method-10x10
	rm -rf Gauss-Seidel_method-10x10eigen
